server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/recommendation/**
          filters:
            - RewritePath=/recommendation/(?<path>.*), /$\{path}